name: littlechef
version: 1.0.0
dependencies:
  angular: "1.1.0"
  web_components: "0.10.1"
  browser: any
  http_server: ">=0.9.3 <0.10.0"
dev_dependencies:
  guinness: "0.1.17"
  mock: any
transformers:
- angular:
    html_files:
      - lib/popular/popular_recipes.html
